### ISSUE TITLE
Output file with final resting positions of nodes

### ISSUE THREAD

**Issue by wolfiex** [HanKruiger/tsNET#1]
A self created file at the end of the run containing all node positions would save you losing all the data each time you close python. This can possibly be triggered using a --save flag?

**Comment by wolfiex** [comment]
Currently crudely implemented using code below but can easily be done in a neater fashion. 
    
       names = [i.split(' ')[0] for i in  tuple(open(args.input_graph))[2:2+g.num_vertices()]]
        f = open('tsnet.out','w')
        for i in g.vertices():
            f.write('%s,%s,%s\n'%(names[int(i)],pos[i][0],pos[i][1]))
        f.close()

**Comment by HanKruiger** [comment]
Thanks for the suggestion! That does seem very useful, and trivial to implement. I'll add this in a few days.
