### ISSUE TITLE
About perplexity

### ISSUE THREAD

**Issue by CherChen0** [HanKruiger/tsNET#3]
Hi, I'm recently doing some experiments on your algorithm. (Thanks for your sharing!)
And I have a question about how to choose a good perplexity parameter. when I use your algorithm on other dataset, sometimes it will always say "The perplexity is probably too low". As is suggested, it seems it only has one proper value. I don't know what's wrong with the X matrix.

**Comment by HanKruiger** [comment]
Hello, and thanks for your interest!

I don't really know what's happening there. All I know is that it's happening in the pre-processing stage where the standard deviations of the Gaussians are sought, to attain the requested perplexity.

You can change the perplexity with the `-p` flag. I assume you've tried increasing it?

Is there anything worth mentioning about the dataset you're using? Is it large? Disconnected? Sparse?

**Comment by CherChen0** [comment]
Thanks for your answer! It's much faster than I thought.

Yes, I have tried changing the perplexity with the -p flag. 

The dataset is disconnected. And the range of perplexity is very very narrow, just like I can only choose exactly one value. But when I deleted the disconnected nodes, the problem has gone.
Maybe the problem is about the disconnected network?

**Comment by HanKruiger** [comment]
Alright, then it's probably related to how distances are set to non-connected vertices.

Right now, those distances are set to *k* times the largest shortest-path distance between any two connected vertices. *k* is set to 10 (relevant code in `modules/distance_matrix.py`), which may be a bit excessive. You can try playing around with that value. I hope that helps!

I'd also gladly accept a pull request where the *k* parameter is exposed to the CLI.

**Comment by CherChen0** [comment]
Yes, I have tried adjusting the k parameter. I also tested other disconnected datasets.  I found the problem only happens when there exist nodes whose degree are zero.( In this situation, adjusting k has little effect) 
I'll try to add the k to the CLI.
Thank you!
