### ISSUE TITLE
Bundling and PivotMDS layouts

### ISSUE THREAD

**Issue by gfalkman** [HanKruiger/tsNET#4]
I came across your paper "Graph Layouts by t-SNE” from 2017 and found it most interesting! I was also happy to see that you had shared your code on GitHub. I’ve played around with the code a little bit and have a couple of questions that I hope you can answer:
- How did you achieve the edge bundling discussed in Sect. 4.7 and shown in some of the figures? Some post-processing of the saved graphs?
- I’m not sure how one could construct a PivotMDS layout for a new graph.

Göran Falkman

**Comment by HanKruiger** [comment]
Hi Göran, thanks for you interest! I hope the following helps.

For the edge bundling, I've used CUBu[1], but I'm not sure if the source code/application is public. I encourage you to contact the original authors listed below, they might be able to help.

I manually used ~~[Gephi](https://gephi.org/)~~ [Tulip](https://en.wikipedia.org/wiki/Tulip_(software)) to contruct and export the PivotMDS layouts from the graphs. Unfortunately, the PivotMDS phase of tsNET* is not incorperated into the graph layout pipeline of this repository, as it relies on the PivotMDS layouts.

[1]: Van der Zwan, Matthew, Valeriu Codreanu, and Alexandru Telea. "CUBu: Universal real-time bundling for large graphs." IEEE transactions on visualization and computer graphics 22.12 (2016): 2550-2563.

**Comment by gfalkman** [comment]
Hi Han,

Thank you for your prompt reply!

Regarding the PivotMDS layouts, I cannot find any Gephi plugin for PivotMDS. Could you please elaborate on how exactly you constructed these layouts using Gephi? Any help on how to do this would be most appreciated.

Best regards,
Göran

27 apr. 2018 kl. 10:46 skrev Han Kruiger <notifications@github.com<mailto:notifications@github.com>>:


Hi Göran, thanks for you interest! I hope the following helps.

For the edge bundling, I've used CUBu[1], but I'm not sure if the source code/application is public. I encourage you to contact the original authors listed below, they might be able to help.

I manually used Gephi<https://gephi.org/> to contruct and export the PivotMDS layouts from the graphs. Unfortunately, the PivotMDS phase of tsNET* is not incorperated into the graph layout pipeline of this repository, as it relies on the PivotMDS layouts.

[1]: Van der Zwan, Matthew, Valeriu Codreanu, and Alexandru Telea. "CUBu: Universal real-time bundling for large graphs." IEEE transactions on visualization and computer graphics 22.12 (2016): 2550-2563.

**Comment by HanKruiger** [comment]
Hi Göran,

Apologies, I may have been remembering incorrectly. During the time of writing I used both Gephi and [Tulip](https://en.wikipedia.org/wiki/Tulip_(software)) for making the various layouts. If there's no PivotMDS in Gephi, I'm pretty sure™ it's in Tulip.

Best,
Han
