### ISSUE TITLE
License

### ISSUE THREAD

**Issue by suvorovrain** [HanKruiger/tsNET#5]
Hello.
I am doing my university homework, part of which is to implement some graph layout algorithm on the plane. I found your very interesting article about tsNET algorithm and wanted to try to implement it in my work. But there is no license specified in your repository, so I have no possibility to use your code. Could you provide me with such an opportunity? Or just specify the license in the repository. I will be extremely grateful to you.

**Comment by HanKruiger** [comment]
Hi there,

Thanks for bringing this to my attention. I have added a license to the repository.
Good luck with your university work!
